name: Test

on:
  pull_request:
    branches:
      - release
      - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    name: crabstep Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo build --no-default-features
      - run: cargo build --features std
      - run: cargo build --features foundation
      - run: cargo clippy --all-targets --all-features
      - run: cargo test --verbose --all-features
